### ISSUE TITLE
Issue with release 2022.4

### ISSUE THREAD

**Issue by abm-Github** [damianniemiec/fs1pg#4]
Hello,
I just upgraded my home assistant to release 2022.4 and my switchs fs1pg don't work anymore.
I saw in the release note 2022.4 that these switchs have been deprecated for all energy-related attributes (current_power_w and today_energy_kwh).
Do you plan to fix this issue?
Thank you in advance for your response.

**Comment by damianniemiec** [comment]
Hi,

I've just created a new release. So far it's marked as pre-release but you can download it (or download again and check beta version if you're using hacs)
