### ISSUE TITLE
Integration Stop Working since Home Assistant 2023.5.0 Update

### ISSUE THREAD

**Issue by Frowxen** [damianniemiec/fs1pg#7]
Integration Stop Working since Home Assistant 2023.5.0 update.

It show this error:

Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/fs1pg/__init__.py:25
Integration: GWF-S171 Smart Wifi Plug (documentation, issues)
First occurred: 16:51:29 (7 occurrences)
Last logged: 17:18:49

Error setting up entry Cafetera for fs1pg
Error setting up entry Frigorífico II for fs1pg
Error setting up entry WiFi Smart Plug 8 for fs1pg
Error setting up entry WiFi Smart Plug 9 for fs1pg
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/fs1pg/__init__.py", line 25, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
![Screenshot_2023-05-04-17-26-00-395_io homeassistant companion android](https://user-images.githubusercontent.com/92628531/236255177-9432bff4-d858-4380-98b1-8930b44df63d.jpg)

**Comment by rifo-m** [comment]
I'm able to "workaround" this by editing `/root/config/custom_components/fs1pg/__init__.py` changing the line:
`hass.config_entries.async_setup_platforms(entry, _PLATFORMS)`
by:
`await hass.config_entries.async_forward_entry_setups(entry, _PLATFORMS)`

References:
https://github.com/vwt12eh8/hassio-ecoflow/issues/76
https://community.home-assistant.io/t/issues-with-nest-protect-after-installing-20230503-1/567537/6
